kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: harbor.blauwelle.com/deepies/go-build:v1.0.2
    environment:
      GIT_SSH_KEY:
        from_secret: GIT_SSH_KEY
    commands:
      - /usr/local/bin/init-ssh-key
      - go mod download
      - mkdir -p build
      - CGO_ENABLED=0 GOOS=linux go build -ldflags "-w -s" -o build/go-admin ./
      - /usr/local/bin/create-tags
  - name: publish
    image: plugins/docker:20.14.0
    when:
      event:
        - tag
    settings:
      dockerfile: docker/Dockerfile.scrm
      repo: harbor.blauwelle.com/deepies/labeler2
      registry: harbor.blauwelle.com
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      mtu: "1450"
